name: darkkick
description: A self-destructing messenger

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.8.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.5.6
  image_picker: ^1.0.4
  local_auth: ^1.1.6
  shared_preferences: ^2.2.2
  encrypt: ^5.0.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true