name: darkkick
description: A self-destructing messenger

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  image_picker: ^1.0.4
  local_auth: ^2.1.8
  provider: ^6.1.0
  flutter_riverpod: ^2.4.9
  firebase_messaging: ^15.0.0
  in_app_purchase: ^3.1.7
  shared_preferences: ^2.2.2
  encrypt: ^5.0.1
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  microphone: ^0.1.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  lottie: ^3.0.0
  rive: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true