name: darkkick_messenger
description: "My Messenger App"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.9.0
  flutter_svg: ^2.0.9  # ДОБАВЬ ЭТУ СТРОКУ

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg  # ДОБАВЬ ЭТУ СТРОКУ